In [1]:
import numpy as np
import pandas as pd
pd.set_option("display.precision", 20)
import logging, sys, math
from importlib import reload
import matplotlib.pyplot as plt
%matplotlib auto
import seaborn as sns
sns.set(style="darkgrid")


Using matplotlib backend: Qt5Agg


In [2]:
if sys.modules.get( 'library', False ) != False :
    del sys.modules['library'] 
    
if sys.modules.get( 'library.Bin', False ) != False :
    del sys.modules['library.Bin'] 
if sys.modules.get( 'Bin', False ) != False :
    del sys.modules['Bin'] 
from library.Bin import *  
logging.warning( "Bin loaded" )

if sys.modules.get( 'library.PositiveBinManager', False ) != False :
    del sys.modules['library.PositiveBinManager'] 
if sys.modules.get( 'PositiveBinManager', False ) != False :
    del sys.modules['PositiveBinManager'] 
from library.PositiveBinManager import *

logging.warning( "PositiveBinManager loaded" )

binTransformer = PositiveBinManager()

In [3]:
binTransformer.createPositiveBins()

processed 2000th positive bin
processed 4000th positive bin
processed 6000th positive bin
processed 8000th positive bin
processed 10000th positive bin
processed 12000th positive bin
processed 14000th positive bin
processed 16000th positive bin
processed 18000th positive bin
processed 20000th positive bin
processed 22000th positive bin
processed 24000th positive bin
processed 26000th positive bin
processed 28000th positive bin
processed 30000th positive bin
processed 32000th positive bin
processed 34000th positive bin
processed 36000th positive bin
processed 38000th positive bin
processed 40000th positive bin
processed 42000th positive bin
processed 44000th positive bin
processed 46000th positive bin
processed 48000th positive bin
processed 50000th positive bin
processed 52000th positive bin
processed 54000th positive bin
processed 56000th positive bin
processed 58000th positive bin
processed 60000th positive bin
processed 62000th positive bin
processed 64000th positive bin
processed 66

In [3]:
b = binTransformer.readPositiveBinById(3)

In [4]:
b

Bin(binId=3, ttf=1.4669954798, data=array([ 2,  4,  1, ...,  3,  3, 10], dtype=int16), quakeIndex=-1, trIndexStart=8191)

In [10]:
data = np.arange(4096)

In [6]:
r1 = data.reshape([64,64])

In [8]:
r2 = data.reshape([64,64,1])

In [7]:
n = (b.data - (-5500)) / (11000)

In [8]:
n[0:10]

array([0.50018182, 0.50036364, 0.50009091, 0.50045455, 0.50072727,
       0.50118182, 0.50090909, 0.50090909, 0.50090909, 0.50081818])

In [24]:
d2=np.append(data, data[-1])

In [25]:
data.shape

(4096,)

In [26]:
d2.shape

(4097,)

In [27]:
d2

array([   0,    1,    2, ..., 4094, 4095, 4095])

In [28]:
d1

NameError: name 'd1' is not defined

In [35]:
l = [data[-1]] *2

In [36]:
l

[4095, 4095]

In [37]:
l * 2

[4095, 4095, 4095, 4095]

In [38]:
d2=np.append(data, l)

In [39]:
d2

array([   0,    1,    2, ..., 4095, 4095, 4095])

In [40]:
d2.shape

(4098,)

In [48]:
d3 = data[-4096:4096]

In [49]:
d3

array([   0,    1,    2, ..., 4093, 4094, 4095])

In [50]:
data[-4096]

0

In [52]:
data[0]

0